version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf4_apache
        ports:
          - 82:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf4:delegated
        depends_on:
          - php

#    mysql:
#        image: mysql
#        command: "--default-authentication-plugin=mysql_native_password"
#        container_name: sf4_mysql
#        volumes:
#            - .docker/data/db:/var/lib/mysql
#        environment:
#            MYSQL_ROOT_PASSWORD: root
#            MYSQL_DATABASE: sf4
#            MYSQL_USER: sf4
#            MYSQL_PASSWORD: sf4 
#        ports:
#          - '3307:3306'

    php:
        build: .docker/php
        container_name: sf4_php
        volumes:
          - .:/home/wwwroot/sf4:delegated
        environment:
          - maildev_host=sf4_maildev 

    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf4_phpmyadmin
        environment:
         - PMA_ARBITRARY=1
        ports:
            - 8089:80
            
            
    php:
        build: .docker/php
        container_name: sf4_php
        volumes:
          - .:/home/wwwroot/sf4:delegated
        environment:
          - maildev_host=sf4_maildev
        depends_on:
          - maildev
#          - mysql
 

    maildev:
        image: djfarrelly/maildev
        container_name: sf4_maildev
        ports:
          - 25
          - 8002:80
          