api_login_check:
    path: /api/login_check

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh 
register:
    path: /api/register
    controller: App\Controller\IndexController::register   
index:
    path: /
    controller: App\Controller\IndexController::redirect_exec 
sample:
    path: /api/sample
    controller: App\Controller\IndexController::redirect_exec 